services:
  frontend:
    build:
      dockerfile: .docker/Dockerfile
    container_name: e60_frontend
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
