services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: e60_frontend
    restart: unless-stopped
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
